import AppBar from 'material-ui/lib/app-bar';
import AppCanvas from 'material-ui/lib/app-canvas';
import AutoComplete from 'material-ui/lib/auto-complete';
import Avatar from 'material-ui/lib/avatar';
import Badge from 'material-ui/lib/badge';
import BeforeAfterWrapper from 'material-ui/lib/before-after-wrapper';
import Card from 'material-ui/lib/card/card';
import CardActions from 'material-ui/lib/card/card-actions';
import CardExpandable from 'material-ui/lib/card/card-expandable';
import CardHeader from 'material-ui/lib/card/card-header';
import CardMedia from 'material-ui/lib/card/card-media';
import CardText from 'material-ui/lib/card/card-text';
import CardTitle from 'material-ui/lib/card/card-title';
import Checkbox from 'material-ui/lib/checkbox';
import CircularProgress from 'material-ui/lib/circular-progress';
import Clearfix from 'material-ui/lib/clearfix';
import DatePicker from 'material-ui/lib/date-picker/date-picker';
import DatePickerDialog from 'material-ui/lib/date-picker/date-picker-dialog';
import Dialog from 'material-ui/lib/dialog';
import Divider from 'material-ui/lib/divider';
import DropDownIcon from 'material-ui/lib/drop-down-icon';
import DropDownMenu from 'material-ui/lib/drop-down-menu';
import EnhancedButton from 'material-ui/lib/enhanced-button';
import FlatButton from 'material-ui/lib/flat-button';
import FloatingActionButton from 'material-ui/lib/floating-action-button';
import FontIcon from 'material-ui/lib/font-icon';
import GridList from 'material-ui/lib/grid-list/grid-list';
import GridTile from 'material-ui/lib/grid-list/grid-tile';
import IconButton from 'material-ui/lib/icon-button';
import IconMenu from 'material-ui/lib/menus/icon-menu';
import LeftNav from 'material-ui/lib/left-nav';
import LinearProgress from 'material-ui/lib/linear-progress';
import List from 'material-ui/lib/lists/list';
import ListDivider from 'material-ui/lib/lists/list-divider';
import ListItem from 'material-ui/lib/lists/list-item';
import Menu from 'material-ui/lib/menus/menu';
import MenuItem from 'material-ui/lib/menus/menu-item';
import Mixins from 'material-ui/lib/mixins';
import Overlay from 'material-ui/lib/overlay';
import Paper from 'material-ui/lib/paper';
import Popover from 'material-ui/lib/popover/popover';
import RadioButton from 'material-ui/lib/radio-button';
import RadioButtonGroup from 'material-ui/lib/radio-button-group';
import RaisedButton from 'material-ui/lib/raised-button';
import RefreshIndicator from 'material-ui/lib/refresh-indicator';
import Ripples from 'material-ui/lib/ripples';
import SelectField from 'material-ui/lib/select-field';
import SelectableEnhance from 'material-ui/lib/hoc/selectable-enhance';
import Slider from 'material-ui/lib/slider';
import SvgIcon from 'material-ui/lib/svg-icon';
import Styles from 'material-ui/lib/styles';
import Snackbar from 'material-ui/lib/snackbar';
import Tab from 'material-ui/lib/tabs/tab';
import Tabs from 'material-ui/lib/tabs/tabs';
import Table from 'material-ui/lib/table/table';
import TableBody from 'material-ui/lib/table/table-body';
import TableFooter from 'material-ui/lib/table/table-footer';
import TableHeader from 'material-ui/lib/table/table-header';
import TableHeaderColumn from 'material-ui/lib/table/table-header-column';
import TableRow from 'material-ui/lib/table/table-row';
import TableRowColumn from 'material-ui/lib/table/table-row-column';
import Toggle from 'material-ui/lib/toggle';
import ThemeWrapper from 'material-ui/lib/theme-wrapper';
import TimePicker from 'material-ui/lib/time-picker';
import TextField from 'material-ui/lib/TextField';
import Toolbar from 'material-ui/lib/toolbar/toolbar';
import ToolbarGroup from 'material-ui/lib/toolbar/toolbar-group';
import ToolbarSeparator from 'material-ui/lib/toolbar/toolbar-separator';
import ToolbarTitle from 'material-ui/lib/toolbar/toolbar-title';
import Tooltip from 'material-ui/lib/tooltip';
import Utils from 'material-ui/lib/utils';
import Menu3 from 'material-ui/lib/svg-icons/navigation/menu';
import ChevronLeft from 'material-ui/lib/svg-icons/navigation/chevron-left';
import ChevronRight from 'material-ui/lib/svg-icons/navigation/chevron-right';

import injectTapEventPlugin from 'react-tap-event-plugin';


let ReactClasses = {};

ReactClasses.AppBar = AppBar;
ReactClasses.AppCanvas = AppCanvas;
ReactClasses.AutoComplete = AutoComplete;
ReactClasses.Avatar = Avatar;
ReactClasses.Badge = Badge;
ReactClasses.BeforeAfterWrapper = BeforeAfterWrapper;
ReactClasses.Card = Card;
ReactClasses.CardActions = CardActions;
ReactClasses.CardExpandable = CardExpandable;
ReactClasses.CardHeader = CardHeader;
ReactClasses.CardMedia = CardMedia;
ReactClasses.CardText = CardText;
ReactClasses.CardTitle = CardTitle;
ReactClasses.Checkbox = Checkbox;
ReactClasses.CircularProgress = CircularProgress;
ReactClasses.Clearfix = Clearfix;
ReactClasses.DatePicker = DatePicker;
ReactClasses.DatePickerDialog = DatePickerDialog;
ReactClasses.Dialog = Dialog;
ReactClasses.Divider = Divider;
ReactClasses.DropDownIcon = DropDownIcon;
ReactClasses.DropDownMenu = DropDownMenu;
ReactClasses.EnhancedButton = EnhancedButton;
ReactClasses.FlatButton = FlatButton;
ReactClasses.FloatingActionButton = FloatingActionButton;
ReactClasses.FontIcon = FontIcon;
ReactClasses.GridList = GridList;
ReactClasses.GridTile = GridTile;
ReactClasses.IconButton = IconButton;
ReactClasses.IconMenu = IconMenu;
ReactClasses.LeftNav = LeftNav;
ReactClasses.LinearProgress = LinearProgress;
ReactClasses.List = List;
ReactClasses.ListDivider = ListDivider;
ReactClasses.ListItem = ListItem;
ReactClasses.Menu = Menu;
ReactClasses.MenuItem = MenuItem;
ReactClasses.Mixins = Mixins;
ReactClasses.Overlay = Overlay;
ReactClasses.Paper = Paper;
ReactClasses.Popover = Popover;
ReactClasses.RadioButton = RadioButton;
ReactClasses.RadioButtonGroup = RadioButtonGroup;
ReactClasses.RaisedButton = RaisedButton;
ReactClasses.RefreshIndicator = RefreshIndicator;
ReactClasses.Ripples = Ripples;
ReactClasses.SelectField = SelectField;
ReactClasses.SelectableEnhance = SelectableEnhance;
ReactClasses.Slider = Slider;
ReactClasses.SvgIcon = SvgIcon;
ReactClasses.Styles = Styles;
ReactClasses.Snackbar = Snackbar;
ReactClasses.Tab = Tab;
ReactClasses.Tabs = Tabs;
ReactClasses.Table = Table;
ReactClasses.TableBody = TableBody;
ReactClasses.TableFooter = TableFooter;
ReactClasses.TableHeader = TableHeader;
ReactClasses.TableHeaderColumn = TableHeaderColumn;
ReactClasses.TableRow = TableRow;
ReactClasses.TableRowColumn = TableRowColumn;
ReactClasses.Toggle = Toggle;
ReactClasses.ThemeWrapper = ThemeWrapper;
ReactClasses.TimePicker = TimePicker;
ReactClasses.TextField = TextField;
ReactClasses.Toolbar = Toolbar;
ReactClasses.ToolbarGroup = ToolbarGroup;
ReactClasses.ToolbarSeparator = ToolbarSeparator;
ReactClasses.ToolbarTitle = ToolbarTitle;
ReactClasses.Tooltip = Tooltip;
ReactClasses.Utils = Utils;
ReactClasses.Menu3 = Menu3;
ReactClasses.ChevronLeft = ChevronLeft;
ReactClasses.ChevronRight = ChevronRight;

injectTapEventPlugin();

module.exports = ReactClasses;