
import RaisedButton from 'material-ui/lib/raised-button';

import injectTapEventPlugin from 'react-tap-event-plugin';

let ReactClasses = {};

ReactClasses.AppBar = AppBar;
ReactClasses.AppCanvas = AppCanvas;
ReactClasses.AutoComplete = AutoComplete;
ReactClasses.Avatar = Avatar;
ReactClasses.Badge = Badge;
ReactClasses.BeforeAfterWrapper = BeforeAfterWrapper;
ReactClasses.Card = Card;
ReactClasses.CardActions = CardActions;
ReactClasses.CardExpandable = CardExpandable;
ReactClasses.CardHeader = CardHeader;
ReactClasses.CardMedia = CardMedia;
ReactClasses.CardText = CardText;
ReactClasses.CardTitle = CardTitle;
ReactClasses.Checkbox = Checkbox;
ReactClasses.CircularProgress = CircularProgress;
ReactClasses.Clearfix = Clearfix;
ReactClasses.DatePicker = DatePicker;
ReactClasses.DatePickerDialog = DatePickerDialog;
ReactClasses.Dialog = Dialog;
ReactClasses.Divider = Divider;
ReactClasses.DropDownIcon = DropDownIcon;
ReactClasses.DropDownMenu = DropDownMenu;
ReactClasses.EnhancedButton = EnhancedButton;
ReactClasses.FlatButton = FlatButton;
ReactClasses.FloatingActionButton = FloatingActionButton;
ReactClasses.FontIcon = FontIcon;
ReactClasses.GridList = GridList;
ReactClasses.GridTile = GridTile;
ReactClasses.IconButton = IconButton;
ReactClasses.IconMenu = IconMenu;
ReactClasses.LeftNav = LeftNav;
ReactClasses.LinearProgress = LinearProgress;
ReactClasses.List = List;
ReactClasses.ListDivider = ListDivider;
ReactClasses.ListItem = ListItem;
ReactClasses.Menu = Menu;
ReactClasses.MenuItem = MenuItem;
ReactClasses.Mixins = Mixins;
ReactClasses.Overlay = Overlay;
ReactClasses.Paper = Paper;
ReactClasses.Popover = Popover;
ReactClasses.RadioButton = RadioButton;
ReactClasses.RadioButtonGroup = RadioButtonGroup;
ReactClasses.RaisedButton = RaisedButton;
ReactClasses.RefreshIndicator = RefreshIndicator;
ReactClasses.Ripples = Ripples;
ReactClasses.SelectField = SelectField;
ReactClasses.SelectableEnhance = SelectableEnhance;
ReactClasses.Slider = Slider;
ReactClasses.SvgIcon = SvgIcon;
ReactClasses.Styles = Styles;
ReactClasses.Snackbar = Snackbar;
ReactClasses.Tab = Tab;
ReactClasses.Tabs = Tabs;
ReactClasses.Table = Table;
ReactClasses.TableBody = TableBody;
ReactClasses.TableFooter = TableFooter;
ReactClasses.TableHeader = TableHeader;
ReactClasses.TableHeaderColumn = TableHeaderColumn;
ReactClasses.TableRow = TableRow;
ReactClasses.TableRowColumn = TableRowColumn;
ReactClasses.Toggle = Toggle;
ReactClasses.ThemeWrapper = ThemeWrapper;
ReactClasses.TimePicker = TimePicker;
ReactClasses.TextField = TextField;
ReactClasses.Toolbar = Toolbar;
ReactClasses.ToolbarGroup = ToolbarGroup;
ReactClasses.ToolbarSeparator = ToolbarSeparator;
ReactClasses.ToolbarTitle = ToolbarTitle;
ReactClasses.Tooltip = Tooltip;
ReactClasses.Utils = Utils;
ReactClasses.Menu3 = Menu3;
ReactClasses.ChevronLeft = ChevronLeft;
ReactClasses.ChevronRight = ChevronRight;

injectTapEventPlugin();

module.exports = ReactClasses;
